### PR TITLE
Implementation of TODIM 🆕

### PR DESCRIPTION
**Pull request by shayandavoodii**
This PR delivers the implementation of the TODIM method as promised in #48. Please review the changes and inform me if there are any issues related to the implementation, unit tests, or any other concerns. Additionally, please let me know if adjustments need to be made to other files to align them with the package's API.

### CODE REVIEW

**Comment by shayandavoodii** [comment]
Please do not merge this until I tackle the missing lines according to Codecov's report.

**Comment by jbytecode** [comment]
Thank you, it seems it works well.

I won't have an action until you ping me.

Please also note that the file 

https://github.com/jbytecode/JMcDM/blob/main/src/normalizations.jl

includes some common standardization methods. MCDM tools now have optional normalization arguments with default values like 

```julia
function topsis(
    decisionMat::Matrix,
    weights::Array{Float64,1},
    fns::Array{F,1}; 
    normalization::G = Normalizations.vectornormnormalization
)::TopsisResult where {F<:Function, G<:Function}
```

would you mind migrating the normalization of todim to normalizations.jl or use an existing one if there is one with the same functionality?

**Comment by shayandavoodii** [comment]
> would you mind migrating the normalization of todim to normalizations.jl or use an existing one if there is one with the same functionality?

Sure! I'll check it out.

**Comment by shayandavoodii** [comment]
@jbytecode, Could you please review the changes? Please let me know if there is anything else to be considered.

**Comment by jbytecode** [comment]
looks nice, thank you!

**Pull request merged**
