### PR TITLE
Implementation of SECA

### PR DESCRIPTION
**Pull request by shayandavoodii**
This PR refers to this issue https://github.com/jbytecode/JMcDM/issues/46
Please review it precisely. I may forget to add specific SECA material in directories other than `src`. If there were any, please mention them so I can handle them. Please let me know if you find any issues with SECA-related lines; I'll be right there.

### CODE REVIEW

**Comment by jbytecode** [comment]
Great work, looks fine! Thank you. 

I will perform the later integration tasks and fix the bugs if exist.

The main tasks I am planning to do:

- Removing the GLPK 
- Adding Ipopt
- Updating documentation
- Adding an extra warning in the documentation that states Ipopt and JuMP should be loaded to use Seca.
- And more.

**Comment by shayandavoodii** [comment]
Thank you for your great support. Please count on me for any help with further justification; it's not my last contribution to this great library. So, I want to make things easy for you in my next contribution by learning related things through this PR in maintaining the library.
Regards.

**Comment by jbytecode** [comment]
Thank you, I'll mention the issue number in my commits and let you know more on the integration process

**Comment by shayandavoodii** [comment]
Thank you so much.
I forgot to mention a point. In the seca.jl, an optimization can be replacing the `!all(iszero, max_idx)` with `sum(max_idx)>0` and `!all(iszero, min_idx)` with `sum(min_idx)>0`. Unfortunately, I'm away from my laptop, so I can't test it. I can't remember whether summing up a bit vector produces the desired result since working with bit vectors is a bit tricky.

**Pull request merged**
